world: world
spawn:
  ==: org.bukkit.Location
  world: world
  x: 163.5
  y: 68.0
  z: -157.5
  pitch: 0.0
  yaw: 0.0
goals:
  - ==: org.bukkit.util.BoundingBox
    minX: 179.9
    minY: 65.0
    minZ: -161.9
    maxX: 181.9
    maxY: 70.0
    maxZ: -153.9
  - ==: org.bukkit.util.BoundingBox
    minX: 147.0
    minY: 65.0
    minZ: -161.9
    maxX: 145.0
    maxY: 70.0
    maxZ: -153.0